spring:
  application:
    name: todolist
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: user22
    driver-class-name: org.postgresql.Driver
springdoc:
    api-docs:
      version: openapi_3_0